name: Docker Image for Frontend

on: 
  push:
    branches: [ main ]
  workflow_dispatch:
      inputs:
        environment:
          type: choice
          description: Select the environment
          required: true
          options:
            - TEST
            - UAT  
 

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.5.2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_PASS }}
            
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        env: 
          IMAGE: ${{ env.DOCKER_IMAGE }} 
        with:
           images: |
              $IMAGE
           tags: |
              type=raw,type=raw,value=main_${{ github.sha }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

