name: Docker Image for Frontend

on: 
  push:
    branches: [ main ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   name: build a docker image for front
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build the Docker image
  #       run: docker build . --file Dockerfile --tag "${GITHUB_REF#refs/heads/}:${GITHUB_SHA}"

  push_to_registry:
    name: Push Docker image to Docker Hub
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.5.2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sclaw
          password: DOBRO1981mag
            
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        env:
          BRANCH: ${GITHUB_REF#refs/heads/}
          SHA: ${GITHUB_SHA}
        with:
           images: |
              sclaw/front
           tags: |
              type=raw, value="$BRANCH:$SHA"
            
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

