name: Docker Image for Frontend

on: 
  push:
    branches: 
      - '*'
        # Pattern matched against refs/tags
    tags:        
      - '*' # Push events to every tag not containing /

jobs:

  push_to_docker_registry:
    name: Push Docker image to Docker Hub
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.5.2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_PASS }}
            
      - name: Docker meta tag
        id: meta_tag
        uses: docker/metadata-action@v4
        if: ${{ contains(github.ref_type, 'tag') }}
        with:
           images: |
              ${{ vars.DOCKER_IMAGE }}      
           tags: |
              type=raw,value=${{ github.ref_name }}
              
      - name: Docker meta branch
        id: meta_branch
        uses: docker/metadata-action@v4 
        if: ${{ contains(github.ref_type, 'branch') }}
        with:
          images: |
              ${{ vars.DOCKER_IMAGE }}      
          tags: |       
              type=raw,value=${{ github.ref_name }}_${{ github.sha }},enable=${{ github.ref == format('refs/heads/{0}', github.ref_name) }}
                 
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta_tag.outputs.tags }}
            ${{ steps.meta_branch.outputs.tags }}


  push_to_aws_registry:
    name: Push Docker image to Docker AWS
    environment: AWS
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.5.2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: north-1
      - name: Login to ECR
        uses: docker/login-action@v2
        with:
            registry: 872112711333.dkr.ecr.north-1.amazonaws.com
      - name: Docker meta tag
        id: meta_tag
        uses: docker/metadata-action@v4
        if: ${{ contains(github.ref_type, 'tag') }}
        with:
          images: |
             ${{ vars.DOCKER_IMAGE }}      
          tags: |
             type=raw,value=${{ github.ref_name }}
            
      - name: Docker meta branch
        id: meta_branch
        uses: docker/metadata-action@v4 
        if: ${{ contains(github.ref_type, 'branch') }}
        with:
          images: |
              ${{ vars.REPO }}      
          tags: |       
              type=raw,value=${{ github.ref_name }}_${{ github.sha }},enable=${{ github.ref == format('refs/heads/{0}', github.ref_name) }}
                  
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta_tag.outputs.tags }}
            ${{ steps.meta_branch.outputs.tags }}