name: Docker Image for Frontend

on: 
  push:
    branches: [ main ]

jobs:

  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DOCKER_REPO == 'sclaw/front' }}
        run: echo "$Greeting $First_Name. Today is $DOCKER_REPO!"
        env:
          First_Name: Mona

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.5.2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sclaw
          password: DOBRO1981mag
            
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
           images: |
            ${{ env.DOCKER_REPO }}
           tags: |
              type=raw,type=raw,value=main_${{ github.sha }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

